mysite/apps/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:blog_id>/', views.detail, name='detail'),
    path('<int:blog_id>/leave_comment',
         views.leave_comment, name='leave_comment'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('blog.urls')),
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
]

mysite/apps/blog/models.py
import datetime
from django.db import models
from django.utils import timezone

class Article(models.Model):
    article_title = models.CharField('Назва статті', max_length=200)
    article_text = models.TextField('Текст статті')
    pub_date = models.DateTimeField('Дата публікації')

    def __str__(self):
        return self.article_title

    def was_published_recently(self):
        return self.pub_date >= (timezone.now() - datetime.timedelta(days=7))

    class Meta:
        verbose_name = "Стаття"
        verbose_name_plural = "Статті"

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    author_name = models.CharField("Ім'я автора", max_length=50)
    comment_text = models.CharField('Текст коментару', max_length=200)

    def __str__(self):
        return self.author_name

    class Meta:
        verbose_name = "Коментар"
        verbose_name_plural = "Коментарі"

mysite/apps/blog/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from .models import Article

def index(request):
    latest_article_list = Article.objects.order_by('-pub_date')
    return render(request, 'blog/list.html', {'latest_article_list': latest_article_list})

def detail(request, blog_id):
    try:
        a = Article.objects.get( id = blog_id )
    except:
        raise Http404("Стаття не знайдена")

    latest_comment_list = a.comment_set.order_by('-id')[:10]

    return render(request, 'blog/detail.html', {'article': a, 'latest_comment_list': latest_comment_list})


def leave_comment(request, blog_id):
    try:
        a = Article.objects.get(id=blog_id)
    except:
        raise Http404("Стаття не знайдена")

    a.comment_set.create( author_name = request.POST['name'], comment_text=request.POST['text'])

    return HttpResponseRedirect( reverse('blog:detail', args=(a.id,)) )

mysite/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link
      rel="stylesheet"
      href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css"
    />
    <link
      rel="stylesheet"
      href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css"
    />

    {% comment %} <link href="https://fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css"/> {% endcomment %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />

    <title>{% block title %}Мій сайт{% endblock %}</title>
  </head>
  <body>
    {% block content %}{% endblock %}
  </body>
</html>

mysite/templates/blog/detail.html
{% extends 'base.html' %}

{% block title %}{{article.article_title}}{% endblock  %}

{% block content %} 

    <h2>{{article.article_title}}</h2>

    <p>{{article.article_text}}</p>

    <em>{{article.pub_date}}</em>

    {% if article.was_published_recently %}
        НОВА СТАТТЯ
    {% endif %}

    <hr>

    <form action="{% url 'blog:leave_comment' article.id %}" method="POST">

        {% csrf_token %}

        <input type="text" placeholder="Ваше ім'я" name="name"> <br/>
        <textarea name="text" required="" placeholder="Текст коментаря" cols="30" rows="10"></textarea> <br/>
        <button type="submit">Залишити коментар</button>
    </form>
        
    <hr>

    {% if latest_comment_list %}
        {% for c in latest_comment_list %}
            <p>
                <strong>{{c.author_name}}</strong>
                <p>{{c.comment_text}}</p>
            </p>
        {% endfor %}
    {% else %}
        Коментарі не знайдено! Станьте першим :)
    {% endif %}

{% endblock  %}

mysite/templates/blog/list.html
{% extends 'base.html' %}

{% block title %}Блог{% endblock  %}

{% block content %} 

    <div>
        <h1><a href="">Django Girls Blog</a></h1>
    </div>
    {% if latest_article_list %}
        {% for a in latest_article_list %}
            <div>
                <a href="{% url 'blog:detail' a.id %}">
                    <div>
                        <p>published: {{a.pub_date}}</p>
                        <h2>{{a.article_title}}</h2>
                        <p>{{a.article_text}}</p>
                    </div>
                </a>
            </div>
            <div>
                {% if a.num_of_comments > 0 %}
                    <p>Кількість коментарів: {{a.num_of_comments}}</p>
                {% endif %}
            </div>
        {% endfor %}
    {% else %}
        Статті не знайдені =(
    {% endif %}

{% endblock  %}